feat(virtio): Adding Virtio-net Support to Cloudlet
virt-do/cloudlet pull request #22
Opened 2024-04-21 19:00 UTC by sylvain-pierrot

# Adding Virtio-net Support to Cloudlet

**Description**:

This Pull Request aims to enhance the functionality of Cloudlet by adding support for virtio-net, a paravirtualized network device.

**Changes Introduced (checklist)**:

Virtio Over MMIO:

- [x] MMIO Device Discovery
  - MMIO provides no generic device discovery mechanism. Under Linux, discovery is performed via the kernel command line. Ref `VMMIO` from [doc](https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html).
- [ ] MMIO Device Register Layout
  - MMIO virtio devices provide a set of memory mapped control registers followed by a device-specific configuration space. Ref [here](https://docs.oasis-open.org/virtio/virtio/v1.3/csd01/virtio-v1.3-csd01.html#x1-1820002).
  
 Related Issues:
 
 #3

2024-04-22 12:01 UTC, Assstra commented on src/vmm/src/core/devices/virtio/net/device.rs
> +        irq: u32,
missing device id ?

2024-04-22 12:04 UTC, Assstra commented on src/vmm/Cargo.toml
> +virtio-blk = { git = "https://github.com/rust-vmm/vm-virtio.git", features = [
Why do you need virtio block device ?

2024-04-29 07:06 UTC, Assstra commented on src/vmm/Cargo.toml
> +virtio-blk = { git = "https://github.com/rust-vmm/vm-virtio.git", features = [
?

2024-04-29 07:21 UTC, sylvain-pierrot commented on src/vmm/Cargo.toml
> +virtio-blk = { git = "https://github.com/rust-vmm/vm-virtio.git", features = [
I removed it

2024-04-29 07:27 UTC, sylvain-pierrot commented on src/vmm/src/core/devices/virtio/net/device.rs
> +        irq: u32,
`id` is of type option. For now, `id` is set to None

2024-04-29 17:27 UTC, Kuruyia requested changes

2024-04-29 17:27 UTC, Kuruyia commented on src/vmm/src/core/vmm.rs
> +        let net = Net::new(
Those can be removed.
```suggestion
        };

        let net = Net::new(
```

2024-04-29 17:27 UTC, Kuruyia commented on src/vmm/src/core/vmm.rs
> +            // }
This can be removed.
```suggestion
```

2024-04-29 17:27 UTC, Kuruyia commented on src/vmm/src/core/devices/virtio/register.rs
> +    // !TODO Register to MmioManager
This can be removed.

```suggestion
```

2024-04-29 18:43 UTC, sylvain-pierrot commented on src/vmm/src/core/vmm.rs
> +            // }
Done

2024-04-29 18:43 UTC, sylvain-pierrot commented on src/vmm/src/core/devices/virtio/register.rs
> +    // !TODO Register to MmioManager
Done

2024-04-29 18:43 UTC, sylvain-pierrot commented on src/vmm/src/core/vmm.rs
> +        let net = Net::new(
Done

2024-04-29 19:03 UTC, Kuruyia approved these changes
LGTM, nice work!

2024-04-29 19:07 UTC, merged